### ISSUE TITLE
Recommendation for URLFetchApp

### ISSUE THREAD

**Issue by khalilchoudhry** [dan-kushnaryov/gas-mock-globals#17]
Hi,

I need to set custom HttpResponse for API calls like in Jest we use mockResolvedValue.
Basically, how can we set custom status, custom response body to HttpResponse to test the APIs better?
If someone can guide or give a suggestion about how the library can be used for this case, that would be helpful.

Great Library, 
Thanks!

**Comment by khalilchoudhry** [comment]
@dan-kushnaryov , @jsarafajr 
I hope you guys have a better plan for this use case.

I can add the functionality myself too but needed your input to discuss what would be the better approach here.

Thanks

**Comment by jsarafajr** [comment]
Hi @khalilchoudhry, currently call to UrlFetchApp.fetch just returns an empty response when you use this library https://github.com/dan-kushnaryov/gas-mock-globals/blob/master/src/url-fetch/UrlFetchApp.js#L5 
You can use jest to patch `UrlFetchApp.fetch` with jest.fn(() => response) to mock implementation for your case, though it won't be an elegant solution.

As a broader solution, I think having a way to mock responses within this library is a good idea in general. I'm thinking about something like this:

```js
import { UrlFetchAppStubConfiguration } from 'gas-mock-globals';

UrlFetchAppStubConfiguration
  .when('http://google.com')
  .return(new HttpResponse.setResponseCode(200).setContentText('hello world'));

UrlFetchApp.fetch('http://google.com').getContentText(); // -> 'hello world'

UrlFetchAppStubConfiguration.reset();

UrlFetchApp.fetch('http://google.com') // -> 'default result'
```

Not sure when I'll have time to implement this though.

**Comment by khalilchoudhry** [comment]
Hi, can you please take a look at [UrlFetchAppStubConfiguration](https://github.com/khalilchoudhry/gas-mock-globals/blob/38b23c46bbe274788c191499bc9ded613dc72bc6/src/url-fetch/classes/UrlFetchAppStubConfiguration.js#L1) class & the [tests](https://github.com/khalilchoudhry/gas-mock-globals/blob/38b23c46bbe274788c191499bc9ded613dc72bc6/__tests__/url-fetch/UrlFetchApp.test.js#L28) for it.

**Comment by jsarafajr** [comment]
Hi @khalilchoudhry, good job! I like it. Feel free to create a PR for this and I'll publish a new version of a package. Plus, probably worth adding an example to the README.

Thanks!
