### ISSUE TITLE
fetchAll function arguments

### ISSUE THREAD

**Issue by khalilchoudhry** [dan-kushnaryov/gas-mock-globals#19]
Hi @jsarafajr , I needed to discuss this issue:

https://github.com/dan-kushnaryov/gas-mock-globals/blob/151c861823bec09ae579d2143a928cc7b7f5bd4a/src/url-fetch/UrlFetchApp.js#L17

Shouldn't this be: 

`static fetchAll (requests) { `

without the rest params because URLFetchApp [takes an array of objects](https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app#parameters_2) which fails when the project runs in a Test environment with these mock globals. The requests argument becomes a 2D array because of this.

I'm adding a few methods for SpreadsheetApp & ScriptApp.getOAuthToken. I'll also add this fix to it.

Thanks

**Comment by jsarafajr** [comment]
@khalilchoudhry yep, you're right 👍
