### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joshsny** [dan-kushnaryov/gas-mock-globals#25]
Hi there,

Great library, thanks so much for creating it! I was just about to start creating exactly the same thing, so I could test a card based add-on using Jest.

I would like to use the code in some of my work, but I'm not sure if I can as there is no license associated to the code. Am I allowed to use this at work? Would you consider adding an MIT license to the repository?

**Comment by jsarafajr** [comment]
Sure, made it to have MIT license.
